### ISSUE TITLE
Invoke-PSMDTemplate on Linux has issues

### ISSUE THREAD

**Issue by nyanhp** [PowershellFrameworkCollective/PSModuleDevelopment#112]
On Linux, Invoke-PSMDTemplate visibly writes to the error stream when using the cmdlet with a template name and no specific store. Haven't had much time to troubleshoot, but might have a look at it this week if it annoys me enough ;) The template is still invoked though.

```powershell
# Sad
Invoke-PSMDTemplate -TemplateName PSFModule -Name PowerOfTelemetry -Parameters @{description = 'Sends telemetry' }

# Happy
Invoke-PSMDTemplate -TemplateName PSFModule -Name PowerOfTelemetry -Parameters @{description = 'Sends telemetry' } -Store PSModuleDevelopment
```  

```
# Error

writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Management.Automation.ItemNotFoundException: Cannot find path '/home/jhp/.local/share/PSFramework/WindowsPowerShell/PSModuleDevelopment/Templates' because it does not exist.
                           at System.Management.Automation.SessionStateInternal.GetChildItems(String path, Boolean recurse, UInt32 depth, CmdletProviderContext context)
                           at System.Management.Automation.ChildItemCmdletProviderIntrinsics.Get(String path, Boolean recurse, UInt32 depth, CmdletProviderContext context)
                           at Microsoft.PowerShell.Commands.GetChildItemCommand.ProcessRecord()
TargetObject          : /home/jhp/.local/share/PSFramework/WindowsPowerShell/PSModuleDevelopment/Templates
CategoryInfo          : ObjectNotFound: (/home/jhp/.local/sh\u2026velopment/Templates:String) [Get-ChildItem], ItemNotFoundException
FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-PSMDTemplate<Process>, /home/jhp/.local/share/powershell/Modules/PSModuleDevelopment/2.2.7.90/PSModuleDevelopment.psm1: line 3297
                        at Invoke-PSMDTemplate<Begin>, /home/jhp/.local/share/powershell/Modules/PSModuleDevelopment/2.2.7.90/PSModuleDevelopment.psm1: line 3528
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1, 0}
```

**Comment by FriedrichWeinmann** [comment]
Sounds like something I should fix :)
Thanks for bringing it up, will look into it and fix it before the next release
