### ISSUE TITLE
Export-PSMDString throws error on pester tests with current PSFModule template

### ISSUE THREAD

**Issue by AndiBellstedt** [PowershellFrameworkCollective/PSModuleDevelopment#122]
Export-PSMDString is trying trim method on empty object.
code is:
`$splatParamValue = $splatParam.Item2.Extent.Text.Trim('"').Trim("'")`

Can be avoided by wrapping into an:
`if ($splatParam)`

Exeption:
[pester.ps1]   Executing strings.Tests.ps1
System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
at Export-PSMDString<Process>, C:\Program Files\WindowsPowerShell\Modules\PSModuleDevelopment\2.2.7.98\PSModuleDevelopment.psm1: line 1592
at <ScriptBlock>, D:\a\1\s\ExchangeLogs\tests\general\strings.Tests.ps1: line 13
at New-Block, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 691
at Describe, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 7719
at <ScriptBlock>, D:\a\1\s\ExchangeLogs\tests\general\strings.Tests.ps1: line 11
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 2724
at Invoke-File, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 2733
at Invoke-BlockContainer, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 2662
at Discover-Test, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 1289
at Invoke-Test, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 2195
at Invoke-Pester<End>, C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.2\Pester.psm1: line 4201
at <ScriptBlock>, D:\a\1\s\ExchangeLogs\tests\pester.ps1: line 51
at <ScriptBlock>, D:\a\1\s\build\vsts-validate.ps1: line 7
at <ScriptBlock>, D:\a\_temp\640e3bbc-1047-466e-8ec5-a38ff8a75dba.ps1: line 3
at <ScriptBlock>, <No file>: line 1

**Comment by FriedrichWeinmann** [comment]
Resolved by yourself in #123 
Thank you very much for fixing this :)
